config/routes.rb
P52::Application.routes.draw do
      
  root :to => "home#index"
  match '/random' => 'home#random'
  resources :projects, :except =>[:show,:index], :constraints => { :id => /.*/ }  do
    member do
        put 'archive'
    end
    get 'admin', :on => :collection
    resources :pictures, :only =>[:new]
  end 
  resources :pictures, :except =>[:index] do
    get 'admin', :on => :collection
  end
  match '/pictures' => 'pictures#globalIndex'
  match '/projects' => 'projects#globalIndex'
  resources :authentications

  devise_for :users
  
  resources :users, :only => [:show, :index], :constraints => { :id => /.*/ } do
    resources :projects, :only =>[:show,:index], :constraints => { :id => /.*/ } do
      get 'feed'
    end
    resources :pictures, :only =>[:index, :show]
  end
  match '/account' => 'users#account'
  match '/users/:id/:size' => 'users#current_project', :constraints => { :id => /.*/ }
  match '/users/:id/recent_tweets' => 'users#recent_tweets', :constraints => { :id => /.*/ }
  match '/users/:id/last_pictures' => 'users#last_pictures', :constraints => { :id => /.*/ }
  match '/users/:id/galleries' => 'users#galleries', :constraints => { :id => /.*/ }
  match '/auth/:provider/callback' => 'authentications#create'

end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Paperclip
  include Mongoid::Timestamps
  
  field :name
  embeds_many :authentications
  references_many :projects, :dependent => :delete
  has_attached_file :avatar,
      :url => "/images/avatars/:id/:style.:extension" ,
      :path           => 'public/images/avatars/:id/:style.:extension',
      :styles => {
        :original => ['1920x1680>', :jpg],
        :square    => ['100x100#',   :jpg],
        :small    => ['150x100#',   :jpg],
        :medium   => ['250x250',    :jpg],
        :large    => ['500x500>',   :jpg]
      }
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  validates_presence_of :name
  validates_uniqueness_of :name, :email, :case_sensitive => false
  def to_param
    name
  end
  def to_s
    name
  end
  
  def pictures
    projects = Project.where(:user_id => id).map(&:_id)
    Picture.desc(:postDate).where(:project_id.in => projects)
  end
  
  def last_picture
    projects = Project.where(:user_id => id).map(&:_id)
    picture= Picture.where(:project_id.in => projects).desc(:postDate).first
    if picture
      picture.url_m
    else
     'picture404.png'
    end
  end
  
  def can_have_project? size
    project= Project.find(:first, :conditions =>{:user_id => id, :size => size, :current => true})
    if project == nil
      true
    else
      false
    end
  end
  def current size
    Project.find(:first, :conditions =>{:user_id => id, :size => size, :current => true})
  end
  
  def authenticated_to_flickr?
    auth = authentications.find(:first, :conditions => { :provider => 'flickr' })
    if auth == nil
      false
    else
      true
    end
  end
  
  def avatar_url
    if Avatar::source.avatar_url_for(self, :size => 75)
      Avatar::source.avatar_url_for(self, :size => 75)
    elsif avatar.url
      avatar.url(:square)
    else
      'picture404.png'
    end
  end
  
  
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!, :except =>[:show, :index]
  before_filter :preload_user
  
  before_filter :load_flickraw, :only=>[:last_pictures, :galleries]
  
  def load_flickraw
    FlickRaw.api_key='52c9226e6d1e5c2452366c0f26e5ee11'
    FlickRaw.shared_secret='7248d7d35fd2b1d5'
    auth = @user.authentications.find(:first, :conditions => { :provider => 'flickr' })
    @auth1 = flickr.auth.checkToken :auth_token => auth['token']
  end
  
 
  def index
    add_crumb 'Users', users_path
    @users = User.desc(:last_sign_in_at).paginate :page => params[:page], :per_page => per_page
  end
  
  def show
    add_crumb 'Users', users_path
    add_crumb @user.name, user_path(@user)
  end
  
  def recent_tweets
      # Exchange your oauth_token and oauth_token_secret for an AccessToken instance.

      def prepare_access_token(oauth_token, oauth_token_secret)
          consumer = OAuth::Consumer.new("APIKey", "APISecret",{ :site => "http://api.twitter.com"})
          # now create the access token object from passed values
          token_hash = { :oauth_token => oauth_token,
                                       :oauth_token_secret => oauth_token_secret
                                   }
          access_token = OAuth::AccessToken.from_hash(consumer, token_hash )
          return access_token
      end
      auth = @user.authentications.find(:first, :conditions => { :provider => 'twitter' })

      # Exchange our oauth_token and oauth_token secret for the AccessToken instance.
      access_token = prepare_access_token(auth['token'], auth['secret'])

      # use the access token as an agent to get the home timeline
      response = access_token.request(:get, "http://api.twitter.com/1/statuses/user_timeline.json")

      render :json => response.body
  end
  
  def last_pictures
    @urls = []
    flickr.photos.search(:user_id => 'me').each do |photo|
      puts photo.to_jso
      @urls << FlickRaw.url_s(photo)
    end
  end
  
  def galleries
    @urls = []
    flickr.photosets.getList.each do |photoset|
      @urls << photoset.to_json
    end
    puts @urls
    
  end
  
  def current_project
    @project = @user.current params[:size]
    render 'projects/show'
  end
  

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/account.html.erb
<ul id="account">
<li><%= link_to "Admin your projects", admin_projects_url%></li>
<li><%= link_to "Admin your pictures", admin_pictures_url%></li>
<li><%= link_to "update your connections to websites", authentications_url%></li>
<li><%= link_to "edit your account", edit_user_registration_path%></li>
<li><%= link_to('Logout', destroy_user_session_path) %></li>
</ul>

app/views/users/index.html.erb
<header class="show_users_header"><h2><%= render_crumbs %></h2></header>
<% @users.each do |user| %>
<article class="index_users">
  		<div><%= link_to image_tag(user.last_picture), user%></div>
<header><%= link_to user.name, user %></header>
</article>
<% end %>
<%= will_paginate @users %>

app/views/users/last_pictures.html.erb
<%@urls.each do |image|%>
	<%=image_tag image%>
<%end%>

app/views/users/show.html.erb
<header class="show_user_header"><h2><%= render_crumbs %></h2></header>
</div>
<div style="clear:both"></div>
<div class="container pictures">
<% @user.pictures.each do |picture| %>
	<article class="index_picture">
	<div><%=link_to image_tag(picture.url_m) , picture.url_b , :rel=>'shadowbox[cat]'%></div>
	<header>by <%= link_to picture.user.name, picture.user%></header>
	</article>
<% end %>
</div>
<div style="clear:both"></div>
<div class="container project">
	<h2>Projects</h2>
	<% @user.projects.each do |project| %>

	<%= link_to project.title, [@user, project]%>
	<%end%>
</div>
<div style="clear:both"></div>
<div class="container">