config/routes.rb
P52::Application.routes.draw do
      
  root :to => "home#index"
  match '/random' => 'home#random'
  resources :projects, :except =>[:show,:index], :constraints => { :id => /.*/ }  do
    member do
        put 'archive'
    end
    get 'admin', :on => :collection
    resources :pictures, :only =>[:new]
  end 
  resources :pictures, :except =>[:index] do
    get 'admin', :on => :collection
  end
  match '/pictures' => 'pictures#globalIndex'
  match '/projects' => 'projects#globalIndex'
  resources :authentications

  devise_for :users
  
  resources :users, :only => [:show, :index], :constraints => { :id => /.*/ } do
    resources :projects, :only =>[:show,:index], :constraints => { :id => /.*/ } do
      get 'feed'
    end
    resources :pictures, :only =>[:index, :show]
  end
  match '/account' => 'users#account'
  match '/users/:id/:size' => 'users#current_project', :constraints => { :id => /.*/ }
  match '/users/:id/recent_tweets' => 'users#recent_tweets', :constraints => { :id => /.*/ }
  match '/users/:id/last_pictures' => 'users#last_pictures', :constraints => { :id => /.*/ }
  match '/users/:id/galleries' => 'users#galleries', :constraints => { :id => /.*/ }
  match '/auth/:provider/callback' => 'authentications#create'

end

app/models/project.rb
class Project
  include Mongoid::Document
  include Mongoid::Timestamps




  field :size, :type => Integer
  field :endingDate, :type => Date
  field :description, :type => String
  field :title, :type => String
  field :current, :type => Boolean
  field :closed, :type => Boolean
  referenced_in :user, :inverse_of => :projects
  references_many :pictures, :dependent => :delete

  attr_protected :size
  validates_presence_of :size
  validates_inclusion_of :size, :in => [365,52,12]
  validates_length_of :title, :minimum=>1, :maximum => 255, :allow_blank => false
  validates_uniqueness_of :title, :scope => :user_id

  def to_param
    title
  end

  def numberOfPictures
    size - pictures.size
  end

  def archive
    closed = false
  end

  def last_picture
    Picture.where(:project_id => id).desc(:postDate).first
  end
  
  def url_s
    picture = Picture.where(:project_id => id).desc(:postDate).first
    if picture
      picture.url_s
    else
     'picture404.png'
    end
  end
  def url_m
    picture = Picture.where(:project_id => id).desc(:postDate).first
    if picture
      picture.url_m
    else
     'picture404.png'
    end
  end

  def can_post_picture?
    (current && !closed && (size > pictures.size))
  end

  def can_have_new_picture?
     return true if last_picture == nil
    case size
    when 12
      last_picture.postDate.strftime("%m") != Time.now.strftime("%m")
    when 52
      last_picture.postDate.strftime("%W") != Time.now.strftime("%W")
    when 365
      last_picture.postDate.strftime("%Y%m%d") != Time.now.strftime("%Y%m%d")
    else false
    end
 
  end
  
 

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_filter :authenticate_user! ,:except =>[:show, :index, :globalIndex, :feed]
  #before_filter :must_be_auth_with_flickr! , :only => [:new,:archive,:edit,:create, :update, :destroy, :admin]
  before_filter :preload_user , :only =>[:show, :index, :feed]
  before_filter :current_user_load, :only =>[:archive,:edit,:create, :update, :destroy, :admin]
  before_filter :preload_project, :only => [:archive,:show, :edit, :update, :destroy, :feed]
  before_filter :user_owns_project! ,:only => [:edit, :update, :destroy]
  before_filter :preload_projects , :only => [:index, :admin]
  def user_owns_project!
    if authenticate_user!
      unless current_user == @project.user
        flash[:alert] = "You're not the right user!"
        redirect_to root_url
      end
    end
  end

  def preload_project
    project_title = params[:id] || params[:project_id]
    @project = Project.asc(:title).where(:user_id => @user.id, :title =>project_title).first
  end

  def preload_projects
    @projects = Project.desc(:updated_at).where(:user_id => @user.id).paginate :page => params[:page], :per_page => per_page
  end
  def globalIndex
    add_crumb 'Projects', projects_path
    @projects = Project.desc(:updated_at).paginate :page => params[:page], :per_page => per_page
    render "index"
  end

  # GET /projects
  # GET /projects.xml
  def index
    add_crumb 'Users', users_path
    add_crumb @user.name, user_path(@user)
    add_crumb 'Projects', user_projects_path(@user)
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.xml
  def show
    add_crumb 'Users', users_path
    add_crumb @user.name, user_path(@user)
    add_crumb 'Projects', user_projects_path(@user)
    add_crumb @project.title, user_project_path(@user,@project)
    @pictures = Picture.where(:project_id => @project.id).paginate :page => params[:page], :per_page => per_page
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @project }
      format.json  { render :json => {:project => @project, :pictures => @pictures} }
    end
  end

  # GET /projects/new
  # GET /projects/new.xml
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @project }
    end
  end

  # GET /projects/1/edit
  def edit

  end

  # POST /projects
  # POST /projects.xml
  def create
    @project = Project.new(params[:project])
    @project.size = params[:project][:size]
    @project.user = current_user
    @project.endingDate = Time.now + @project.size.days if @project.size
    @project.current = true
    @project.closed = false

    respond_to do |format|
      if !current_user.can_have_project? @project.size
        format.html { redirect_to(user_projects_url(current_user), :alert => 'YOU ALREADY HAVE THAT KIND OF PROJECT') }
        format.xml  { head :forbidden}
      else
        if @project.save
          format.html { redirect_to([@project.user, @project], :alert => 'Project was successfully created.') }
          format.xml  { render :xml => @project, :status => :created, :location => @project }
        else
          format.html { render :action => "new" }
          format.xml  { render :xml => @project.errors, :status => :unprocessable_entity }
        end
      end

    end
  end

  # PUT /projects/1
  # PUT /projects/1.xml
  def update
    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to([@project.user, @project], :notice => 'Project was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @project.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  def archive
    @project.closed = true
    @project.current = false
    respond_to do |format|
      if @project.save
        format.html { redirect_to([@project.user, @project], :notice => 'Project was successfully archived.') }
        format.xml  { head :ok }
      else
        format.html { redirect_to([@project.user, @project], :alert => 'Project was not archived.') }
        format.xml  { render :xml => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.xml
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to(projects_url) }
      format.xml  { head :ok }
    end
  end
  
  def admin 
  end
  
  def feed
    respond_to do |format|
      format.atom
    end
  end
  
  
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def validProjectSizes
    [365,52,12]
  end
  
  def user_owns_project? project
    if user_signed_in?
      if current_user == project.user
        return true
      end
      
    end
    return false
  end
  
  
  
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
	    <%= f.label :size , 'Size : '%>
		<% validProjectSizes.each() do |size|%>
	    <label><%= radio_button_tag 'project[size]', size %> <span><%=size%></span></label>
	    <%end%>
  </div>
  <div class="field">
    <%= f.text_field :title, :placeholder => 'Title' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/_form_edit.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/admin.html.erb
<% @projects.each do |project| %>
	<article class="admin_project">
  	<div><%= link_to image_tag(project.url_m), [project.user,project] %></div>
	<header><a href='<%= user_project_path(project.user,project)%>'><%= project.size %> - <%= project.title %></a><br/>
   	<%= link_to 'Edit', edit_project_path(project) if (user_owns? project ) %> I
	<%= link_to '+ Picture', new_project_picture_path(project) if (user_owns? project ) %> I
    <%= link_to 'Destroy', project, :confirm => 'Are you sure?', :method => :delete if (user_owns? project )%> I
	<%= link_to('Archive', archive_project_path(project), :confirm => 'Are you sure?', :method => :put)if (user_owns? project)%>
	</header>
	</article>
<% end %>
<%= will_paginate @projects %>

app/views/projects/edit.html.erb
<%= render 'form_edit' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<header class="show_projects_header"><h2><%= render_crumbs %></h2></header>
<% @projects.each do |project| %>
	<article class="index_project">
  	<div><%= link_to image_tag(project.url_m), [project.user,project] %></div>
	<header><a href='<%= user_project_path(project.user,project)%>'><%= project.size %> - <%= project.title %></a></header>
	<span class="index_project_buttons">
   	<%= link_to 'Edit', edit_project_path(project) if (user_owns? project ) %>
    <%= link_to 'Destroy', project, :confirm => 'Are you sure?', :method => :delete if (user_owns? project )%>
	<%= link_to('Archive', archive_project_path(project), :confirm => 'Are you sure?', :method => :put)if (user_owns? project)%>
	</span>
	</article>
<% end %>
<%= will_paginate @projects %>

app/views/projects/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<% content_for :atom do%>
	<%= auto_discovery_link_tag(:atom, project_feed_url(@project.user,@project, :format=>"atom"))%>
<% end %>

<header class="show_project_header">
  <h2><%= render_crumbs %></h2>
  

  

  <span class="archive_project"><%= @project.numberOfPictures %> / <%= @project.size %>  <% if @project.closed %> ARCHIVED<%end%>
<% if !@project.description.blank? %><%= @project.description %> <%end%></span>
</header>
</div>
<div style="clear:both"></div>
<div class="container pictures">
	<% @pictures.each do |picture| %>
		<article class="index_project">
		<div><%=link_to image_tag(picture.url_m) , picture.url_b , :rel=>'shadowbox[cat]'%></div>
		<header>by <%= link_to picture.user.name, picture.user%></header>
	    <span class="index_picture_buttons"<%= link_to 'Edit', edit_picture_path(picture) if user_owns? picture%>
	    <%= link_to 'Destroy', picture, :confirm => 'Are you sure?', :method => :delete if user_owns? picture %></span>
		</article>
<% end %>
<%= will_paginate @pictures %>