config/routes.rb
P52::Application.routes.draw do
      
  root :to => "home#index"
  match '/random' => 'home#random'
  resources :projects, :except =>[:show,:index], :constraints => { :id => /.*/ }  do
    member do
        put 'archive'
    end
    get 'admin', :on => :collection
    resources :pictures, :only =>[:new]
  end 
  resources :pictures, :except =>[:index] do
    get 'admin', :on => :collection
  end
  match '/pictures' => 'pictures#globalIndex'
  match '/projects' => 'projects#globalIndex'
  resources :authentications

  devise_for :users
  
  resources :users, :only => [:show, :index], :constraints => { :id => /.*/ } do
    resources :projects, :only =>[:show,:index], :constraints => { :id => /.*/ } do
      get 'feed'
    end
    resources :pictures, :only =>[:index, :show]
  end
  match '/account' => 'users#account'
  match '/users/:id/:size' => 'users#current_project', :constraints => { :id => /.*/ }
  match '/users/:id/recent_tweets' => 'users#recent_tweets', :constraints => { :id => /.*/ }
  match '/users/:id/last_pictures' => 'users#last_pictures', :constraints => { :id => /.*/ }
  match '/users/:id/galleries' => 'users#galleries', :constraints => { :id => /.*/ }
  match '/auth/:provider/callback' => 'authentications#create'

end

app/models/picture.rb
class Picture
  include Mongoid::Document
  include Mongoid::Paperclip
  include Mongoid::Timestamps
  
  cattr_reader :per_page
  @@per_page = 3
  
  field :pictureId, :type => Integer
  field :postDate, :type => Time
  field :description, :type => String
  field :title, :type => String
  referenced_in :project, :inverse_of => :pictures
  field :flickr, :type => Hash
  has_attached_file :image,
    :styles => { :medium => "300x300>", :thumb => "100x100>", :square => "300x300#" , :web =>"1000x1000>"},
    :storage => :googlestorage,
    :bucket => "eatcpcks",
    :path => "p52/:attachment/:id/:style.:extension",
    :google_storage_credentials => "#{RAILS_ROOT}/config/storage.yml"
    
    
    validates_presence_of :flickr, :unless => :image
    validates_presence_of :image, :unless => :flickr
    validate :one_or_the_other
    def one_or_the_other
    
      if (!image.file? && flickr.blank?)
        errors.add_to_base("You must either upload a file or choose one from flickr!")
      end
    end
    # Paperclip Validations
    #validates_attachment_presence :image
    #validates_attachment_content_type :image, :content_type => ['image/jpeg', 'image/pjpeg', 'image/jpg']
    #validates_attachment_size :image, :less_than => 10.megabytes,
    #    :message => 'filesize must be less than 10 MegaBytes'
    #  validates_attachment_content_type :image, :content_type => [ 'image/jpeg' ],
    #                :message => 'file must be of filetype .jpeg'
  def user
    project.user
  end
  
  def name
    if flickr
      flickr["title"]
    else
      title
    end
  end
 
 
  PHOTO_SOURCE_URL='http://farm%s.static.flickr.com/%s/%s_%s%s.%s'.freeze
 
  def url()
      
    return PHOTO_SOURCE_URL % [flickr['farm'], flickr['server'], flickr['id'], flickr['secret'], "",   "jpg"] if flickr
    return image.url
  end
  def url_m()
     return PHOTO_SOURCE_URL % [flickr['farm'], flickr['server'], flickr['id'], flickr['secret'], "_m", "jpg"] if flickr
     return image.url(:medium)
  end
  def url_s()
     return PHOTO_SOURCE_URL % [flickr['farm'], flickr['server'], flickr['id'], flickr['secret'], "_s", "jpg"] if flickr
     return image.url(:square)
  end
  def url_t()
     return PHOTO_SOURCE_URL % [flickr['farm'], flickr['server'], flickr['id'], flickr['secret'], "_t", "jpg"] if flickr
     return image.url(:thumb)
  end
  def url_b()
     return PHOTO_SOURCE_URL % [flickr['farm'], flickr['server'], flickr['id'], flickr['secret'], "_b", "jpg"] if flickr
     return image.url(:web)
  end
  def url_z()
     return PHOTO_SOURCE_URL % [flickr['farm'], flickr['server'], flickr['id'], flickr['secret'], "_z", "jpg"] if flickr
     return image.url(:web)
  end
  def url_o()
     return PHOTO_SOURCE_URL % [flickr['farm'], flickr['server'], flickr['id'], flickr['secret'], "_o", "jpg"] if flickr
     return image.url
  end
 
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_filter :authenticate_user! ,:except =>[:show, :index, :globalIndex]
  #before_filter :must_be_auth_with_flickr! , :only => [:new,:archive,:edit,:create, :update, :destroy, :admin]
  before_filter :preload_user, :only =>[:show,:index]
  before_filter :current_user_load, :only =>[:new,:edit,:create, :update, :destroy, :admin]

  before_filter :must_have_active_project! , :only=>[:new,:create,:update,:edit, :destroy]

  before_filter :preload_picture!, :except=>[:globalIndex, :new,:index,:create, :admin]
  before_filter :load_flickraw, :only=>[:create, :new, :edit, :update]
  before_filter :preload_new_edit, :only=>[:new, :create]
  before_filter :charge_image_from_params , :only => [:create]
  before_filter :verify_image! , :only=>[:create]
  before_filter :preload_pictures, :only=>[:index, :admin]
  require "kconv"
  def preload_new_edit

      #@pictures = flickr.photos.search(:user_id => 'me')
      @project = Project.find(:first, :conditions => {:title =>params[:project_id], :user_id =>@user.id}) if (params[:project_id])
      @projects = Project.find(:conditions => {:user_id => @user.id})
      back_to = 32
      back_to = (365/@project.size)+1 if @project

      @pictures = flickr.photos.search(:user_id => 'me', :min_upload_date => (Time.now-back_to.day).to_i , :max_upload_date => Time.now.to_i ) if @auth1

  end

  def preload_picture!
    @picture = Picture.find(params[:id])
    if(params[:user_id] && !(@user.pictures.include? @picture))
      redirect_to @picture
    end

  end
  def load_flickraw
    FlickRaw.api_key='52c9226e6d1e5c2452366c0f26e5ee11'
    FlickRaw.shared_secret='7248d7d35fd2b1d5'
    @auth = @user.authentications.find(:first, :conditions => { :provider => 'flickr' })

    @auth1 = flickr.auth.checkToken(:auth_token => @auth['token']) if @auth
  end

  def must_have_active_project!
    projects = Project.where(:user_id => current_user.id, :closed => false, :current => true).all
    if projects.empty?
      #false
      redirect_to new_project_path
    else
      #true
    end
  end

  def charge_image_from_params
    @picture = Picture.new(params[:picture])
  end

  def verify_image!
    if !@picture.project.can_post_picture?
      format.html { redirect_to([current_user,@picture.project], :notice => 'THIS PROJECT DOES NOT ACCEPT ANY NEW PICTURES') }
      format.xml  { head :forbidden}
    elsif !@picture.project.can_have_new_picture?
      format.html { redirect_to([current_user,@picture.project], :notice => 'YOU ALREADY POSTED ONE PICTURE FOR THIS PROJECT DURING THE CURRENT PERIOD') }
      format.xml  { head :forbidden}
    end

  end

  def preload_pictures
    projects = Project.where(:user_id => @user.id).map(&:_id)
    @pictures = Picture.desc(:postDate).where(:project_id.in => projects).desc(:postDate).paginate :page => params[:page], :per_page => per_page
    
  end

  def globalIndex
    add_crumb 'Pictures', pictures_path
    @pictures = Picture.desc(:postDate).paginate :page => params[:page], :per_page => per_page 
    render :index
  end

  # GET /pictures
  # GET /pictures.xml
  def index
    add_crumb 'Users', users_path
    add_crumb @user.name, user_path(@user)
    add_crumb 'Pictures', user_pictures_path(@user)
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @pictures }
    end
  end

  # GET /pictures/1
  # GET /pictures/1.xml
  def show
    add_crumb('Users', users_path) if @user
    add_crumb(@user.name, user_path(@user)) if @user
    add_crumb('Pictures', user_pictures_path(@user)) if @user
    add_crumb 'Pictures', pictures_path unless @user
    add_crumb(@picture.name, user_picture_path(@user, @picture)) if @user
    add_crumb(@picture.name, picture_path(@picture)) unless @user
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @picture }
    end
  end

  # GET /pictures/new
  # GET /pictures/new.xml
  def new
    @picture = Picture.new
    @picture.project = @project
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @picture }
    end
  end

  # GET /pictures/1/edit
  def edit

  end

  # POST /pictures
  # POST /pictures.xml
  def create

    @picture.postDate = Time.now
    if (@picture.flickr)
      hash = Hash.try_convert flickr.photos.getInfo(:photo_id => @picture.flickr)
      hash.each do |key, value|
        if (value.class.to_s =~ /^FlickRaw/)
          hash.delete(key)
        end
      end
      @picture.flickr = hash
    end
    respond_to do |format|
      if @picture.save
        if (@picture.project.pictures.size == @picture.project.size)
          p = @picture.project
          p.closed=true
          p.current = false
          p.save
        end
        format.html { redirect_to([@picture.user,@picture], :notice => 'Picture was successfully created.') }
        format.xml  { render :xml => @picture, :status => :created, :location => @picture }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @picture.errors, :status => :unprocessable_entity }
      end

    end
  end

  # PUT /pictures/1
  # PUT /pictures/1.xml
  def update

    if (params[:picture][:flickr])
      hash = Hash.try_convert flickr.photos.getInfo(:photo_id => params[:picture][:flickr])
      hash.each do |key, value|
        if (value.class.to_s =~ /^FlickRaw/)
          puts 'delete #{key}'
          hash.delete(key)
        end
      end
      params[:picture][:flickr] = hash
    end
    respond_to do |format|
      if @picture.update_attributes(params[:picture])
        format.html { redirect_to(@picture, :notice => 'Picture was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @picture.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.xml
  def destroy

    @picture.destroy

    respond_to do |format|
      format.html { redirect_to(admin_pictures_url) }
      format.xml  { head :ok }
    end
  end


  def admin
  end
end

app/helpers/pictures_helper.rb
module PicturesHelper
  
  def user_owns_picture? picture
    if user_signed_in?
      if current_user == picture.user
        return true
      end
      
    end
    return false
  end
end

app/views/pictures/_form.html.erb
<%= form_for(@picture, :html => {:multipart => true}) do |f| %>
  <% if @picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
      <% @picture.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    
	<% if @project%>
		<%= f.hidden_field :project_id%>
	<%else%>
		<%= f.label :project, 'Project : ' %><%= f.collection_select(:project_id, @projects, :id, :title) %>
	<%end%>
  </div>
<div id="accordion">
	<h3><a href="#">Flickr:</a></h3>
<div class="field <%if @auth%>flickr<%end%>">
	<%if @auth%>
		<% if @pictures.blank?%>
			<%= link_to('Sorry, you didn\'t uploaded a picture to flickr during last period (month, week, two days)', authentications_path, :class=> 'alert') %>
		<%end%>
  	
	<% @pictures.each do |pic| %>
		<label>
			<%= radio_button_tag "picture[flickr]" , pic.id,(@picture.flickr && (@picture.flickr['id'] == pic.id))%>
			<%= image_tag FlickRaw.url_s pic %>
			</label>

	<% end %>
	
  
	<%else%>
	<%= link_to('Authenticate', authentications_path, :class=> 'alert') %>
	<%end%>
	</div>
	<h3><a href="#">Upload a File</a></h3>
  <div class="field">
	<%=f.file_field :image%>
  </div>
</div>
  <div class="actions">
    <%= f.submit 'Publish' %>
  </div>
<% end %>

app/views/pictures/_form_edit.html.erb
<%= form_for(@picture) do |f| %>
  <% if @picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
      <% @picture.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
		<%= f.label :title %><br />
		<%= f.text_field(:title) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pictures/admin.html.erb
<% @pictures.each do |picture| %>
	<article class="admin_picture">
	<div><%=link_to image_tag(picture.url_m) , picture.url_b , :rel=>'shadowbox[cat]'%></div>
	<header><%= link_to 'Edit', edit_picture_path(picture) if user_owns? picture%> I
    <%= link_to 'Destroy', picture, :confirm => 'Are you sure?', :method => :delete if user_owns? picture %></header>
	</article>
<% end %>
<%= will_paginate @pictures %>

app/views/pictures/edit.html.erb
<%= render 'form_edit' %>

<%= link_to 'Show', @picture %> |
<%= link_to 'Back', pictures_path %>

app/views/pictures/index.html.erb
<header class="show_projects_header"><h2><%= render_crumbs %></h2></header>
<% @pictures.each do |picture| %>
	<article class="index_picture">
	<div><%=link_to image_tag(picture.url_m) , picture.url_b , :rel=>'shadowbox[cat]'%></div>
	<header><%= link_to picture.name, picture%> by <%= link_to picture.user.name, picture.user%></header>
	</article>
<% end %>
<%= will_paginate @pictures %>

app/views/pictures/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', pictures_path %>

app/views/pictures/show.html.erb
<header class="show_projects_header"><h2><%= render_crumbs %></h2></header>
<article class="show_picture">
	
<%=image_tag @picture.url_b%><br/>
<!--<header class="show_picture_header">
  <%= @picture.name if (@picture.name && !@picture.name.empty?)%> <%= 'This picture is' if (!@picture.name || @picture.name.empty?)%> in <%= link_to @picture.project.title, [@picture.user,@picture.project] %>
By <%= @picture.user.name%>
</header>-->
  </article>