config/routes.rb
P52::Application.routes.draw do
      
  root :to => "home#index"
  match '/random' => 'home#random'
  resources :projects, :except =>[:show,:index], :constraints => { :id => /.*/ }  do
    member do
        put 'archive'
    end
    get 'admin', :on => :collection
    resources :pictures, :only =>[:new]
  end 
  resources :pictures, :except =>[:index] do
    get 'admin', :on => :collection
  end
  match '/pictures' => 'pictures#globalIndex'
  match '/projects' => 'projects#globalIndex'
  resources :authentications

  devise_for :users
  
  resources :users, :only => [:show, :index], :constraints => { :id => /.*/ } do
    resources :projects, :only =>[:show,:index], :constraints => { :id => /.*/ } do
      get 'feed'
    end
    resources :pictures, :only =>[:index, :show]
  end
  match '/account' => 'users#account'
  match '/users/:id/:size' => 'users#current_project', :constraints => { :id => /.*/ }
  match '/users/:id/recent_tweets' => 'users#recent_tweets', :constraints => { :id => /.*/ }
  match '/users/:id/last_pictures' => 'users#last_pictures', :constraints => { :id => /.*/ }
  match '/users/:id/galleries' => 'users#galleries', :constraints => { :id => /.*/ }
  match '/auth/:provider/callback' => 'authentications#create'

end

app/views/layouts/_menu.html.erb
<li><%=link_to 'Users', users_path%></li>
<li><%=link_to 'Projects', projects_path%></li>
<li><%=link_to 'Pictures', pictures_path%></li>

app/views/layouts/_menu_auth.html.erb
<% if user_signed_in? %>
 <li><%= link_to '+ Project', new_project_path %></li><li> <%= link_to '+ Picture', new_picture_path %></li>
<% elsif user_signed_in? %>
  <li>
  
  </li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>fifty.tw | once a time</title>
<link href='http://fonts.googleapis.com/css?family=Arvo:regular,bold' rel='stylesheet' type='text/css'>

  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>

  <%= csrf_meta_tag %>
  <%= yield :atom %>
  <script>
	$(document).ready(function(){

	    var options = {
	        resizeLgImages:     true,
	        displayNav:         true,
	        handleUnsupported:  'remove',
	        keysClose:          ['c', 27] // c or esc
	    };

	    Shadowbox.init(options);
		$('#shadowButton').click(function(){
			$('a[rel^="shadowbox"]').toggle();
			$('a[rel^="shadowbox"]').next().toggle();
			if($(this).css('opacity')<1)
				$(this).css('opacity',1);
			else
				$(this).css('opacity',0.2);
			return false;
			
		
		});
		if($('.alert').html() == '') $('.alerts').hide();
		$('#close_alerts').click(function(){
			$(this).parent().hide();
			return false;
		});
		$("#accordion").accordion({ active: 1 });
		$('.hmenu li:not(:last)').after('<li>•</li>');
		
		<%if current_page?(root_url) && !user_signed_in? && !params[:page] %>
			$('.container:not(.main)').hide();
			$('#take_a_look').click(function(){
				
				$('.container.main').fadeOut(function(){$('.container:not(.main)').fadeIn();});
				return false;
			});
		<%end%>
	});
  </script>
</head>
<body>
	<header class="main">
		
		<div id="title"><img src="/images/backlogo.png"/><span><%= link_to '52'.upcase , '/'%></span></div>
		<div id="menubar">
		<nav class="hmenu <% if !user_signed_in? %>small<%end%>">
		  <%= render 'layouts/menu' %>
		  <%= render 'layouts/menu_auth' %>
		<%= render 'devise/menu/login_items' %>
		<%= render 'devise/menu/registration_items' %>
		</nav>
		<!--<a id="shadowButton" href="#">BOX</a>-->
		</div>
	</header>
	<span class="alerts">
	<p class="alert"><%= alert %></p><a id="close_alerts" href="#close">[close]</a></span>
	<div class="container main">
	<%= yield %>
	</div>
	<footer>
		<p id="footerAbout">Design & code by <a href="mailto:yannick@eatcupcak.es">eatcpcks</a></p>
	</footer>
	<script type="text/javascript">

	  var _gaq = _gaq || [];
	  _gaq.push(['_setAccount', 'UA-3868259-8']);
	  _gaq.push(['_trackPageview']);

	  (function() {
	    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
	    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
	    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
	  })();

	</script>
</body>
</html>